# site settings
title: Helena Wang
subtitle: engineer. artist.
email: hello@helenas.page
description: Hello. I'm Helena. I make things.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://www.helenas.page # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (617) 308-9086

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/aihelena
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown
plugins:
  -jekyll-seo-tag

sass:
  style: compressed
